version: '3.8'
services: 
  jenkins:
    image: jenkins/jenkins
    ports:
     - 6060:8080
    networks:
     - network1
  qaserver:
    image: tomcat
    ports:
     - 7070:8080
    networks:
      - network2
  prodserver:
    image: tomcat
    ports:
      - 8080:8080
    networks:
      - network2
networks:
 network1: {}
 network2: {}
