---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    author: Syed
spec:
  containers:
   - name: redis
     image: redis
     ports:
       - containerPort: 6379
...

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    name: redis-pod
    author: Syed
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

...