---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    app: webapp
spec:
  containers:
  - name: tomcat-container
    image: tomcat:9.0
    ports:
    - name: app-port
      containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - port: 8080 #expose within the cluster
    nodePort: 30002 #expose to internet
    targetPort: 8080 #container-port
    protocol: TCP
  selector:
    app: webapp
  type: NodePort

...