apiVersion: v1
kind: config

proxy_url: https://proxy.host:3128

clusters:
- cluster:
  name: development
    certificate-authority-data:

    server: https://api.kubernetes.ssdevops.in:6443

users:
- name: developer

contexts:
- context: 
  name: development
