apiVersion: apps/v1
kind: Deployment
metadata:
  name: sscademy-app
  labels: 
    app: sscademy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sscademy-app
  template:
    metadata:
      labels:
        app: sscademy-app
    spec:
      containers:
      - name: sscademy-app
        image: {{ .Values.appimage }}
        ports:
        - name: app-port
          containerPort: 8080
      
