---

- name: Configure server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP on Centos
      yum:
        name: ntp
        state: present
      when: ansible_distribution == "CentOS"
    
    - name: Install NTP on Ubuntu
      apt:
        name: ntp
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Start & Enable NTP on RedHat
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start & Enable NTP on Debian
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
