---

- name: Server configuration
  hosts: all
  vars:
    ntp_path: "{{ntp_path}}"
  tasks:
   - name: Install NTP on Centos
     yum:
      name: ntp
      state: present
     when: ansible_distribution == "CentOS"

   - name: Install NTP on Ubuntu
     apt:
       update_cache: yes
       name: ntp
       state: present
     when: ansible_distribution == "Ubuntu"

   - name: Start NTP service on RedHat machines
     service:
      name: ntpd
      state: started
      enabled: yes
     when: ansible_os_family == "RedHat"

   - name: Start NTP service on Debian machines
     service:
      name: ntp
      state: started
      enabled: yes
     when: ansible_os_family == "Debian"

   - name: Banner file /etc/motd
     copy:
      content: "{{data}}"
      dest: /etc/motd

   - name: Deploy NTP conf on Debian machines
     template:
       src: template/ntp_debian.conf.j2
       dest: "{{ntp_path}}"
     when: ansible_os_family == "Debian"
     notify:
       - restart ntp service on Debian

   - name: Deploy NTP conf on RedHat machines
     template:
       src: template/ntp_redhat.conf.j2
       dest: "{{ntp_path}}"
     when: ansible_os_family == "RedHat"
     notify:
      - restart ntp service on RedHat

   - name: Create a directory for DEV
     file:
      path: /etc/devdata
      state: directory
      mode: 0742

   - name: Deploy dev data file
     copy:
       src: file/dev.txt
       dest: /opt/devdata/dev.txt

  handlers:
   - name: restart ntp service on Debian
     service:
      name: ntp
      state: restarted
     when: ansible_os_family == "Debian"

   - name: restart ntp service on RedHat
     service:
       name: ntpd
       state: restarted
     when: ansible_os_family == "RedHat"