---

- name: Server configuration
  hosts: all
  roles:
    - role: server-conf
      vars:
        ntp0: 0.europe.pool.ntp.org
        ntp1: 1.europe.pool.ntp.org
        ntp2: 2.europe.pool.ntp.org
        ntp3: 3.europe.pool.ntp.org
  
  

  