---
- name: Setup WebServer
  hosts: webservergrp
  become: yes
  tasks:
    - name: Install Apache HTTPD
      yum: 
        name: httpd
        state: present
    - name: Start and Enable HTTPD
      service: 
        name: httpd
        state: started
        enabled: yes

- name: Setup DBServer
  hosts: dbservergrp
  tasks: 
    - name: Install postgresql
      yum:
        name: postgresql
        state: present
    - name: Start and Enable postgresql
      service:
        name: postgres
        state: started
        enabled: yes
...
