---
- name: Setup DBServer
  hosts: dbservergrp
  become: yes
  vars:
    dbname: devopsgroup
    dbuser: devops
    dbpass: admin123
  tasks:
    - debug:
        var: dbname

    - debug:
        msg: "Value of dbuser is {{dbuser}}"
        
    - name: Install MYSQL server
      yum: 
        name: mariadb-server
        state: present

    - name: Install Python MYSQL
      yum: 
        name: MYSQL-python
        state: present
            
    - name: Start & Enable mariadb service
      service:
        name: mariadb
        state: started 
        enabled: yes
    - name: Create a database with name 'accounts'
      mysql_db:
        name: "{{dbname}}"
        state: present
    - name: Create database user with name 'admin'
      mysql_user: 
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        